const MODELS = [
  {
    "id": "A",
    "name": "回声司仪",
    "en": "ECHO USHER",
    "image": "atomic_desktop/A_回声司仪.png",
    "hook": "面罩滑开、虹膜对焦与机械手行礼。",
    "motion": "对焦 → 开面罩 → 指挥手势 → 鞠躬复位",
    "controls": "面罩锁、手势拨片、节拍旋钮",
    "fit": "手部收回必须避开档案架；总高建议不超过 1.45D。",
    "group": "original",
    "status": "原有设定"
  },
  {
    "id": "B",
    "name": "孵日器",
    "en": "HELIOS INCUBATOR",
    "image": "atomic_desktop/B_孵日器.png",
    "hook": "已经在桌面运行的第一台装置。",
    "motion": "六瓣绽放 → 核心升起 → 万向环加速 → 放电退潮",
    "controls": "保留当前七个实体按钮",
    "fit": "以当前真实底座作为所有装置的基准。",
    "group": "original",
    "status": "本机开发版",
    "actual": "runtime_preview/B.png"
  },
  {
    "id": "C",
    "name": "逆时水母",
    "en": "CHRONO MEDUSA",
    "image": "atomic_desktop/C_逆时水母.png",
    "hook": "会倒着呼吸的机械时钟与仿生触须。",
    "motion": "钟罩抬升 → 配重交换 → 触须展开 → 倒序回摆",
    "controls": "逆时拨杆、相位旋钮、钟罩释放键",
    "fit": "触须不能落进按钮和档案架的空间。",
    "group": "original",
    "status": "原有设定"
  },
  {
    "id": "D",
    "name": "偏心方舟",
    "en": "PARADOX CABINET",
    "image": "atomic_desktop/D_偏心方舟.png",
    "hook": "倾斜方匣里，几只机械手突然探出。",
    "motion": "支架摆正 → 壳板展开 → 小手探出 → 匣体偏转",
    "controls": "姿态拨杆、面板锁键、手势触键",
    "fit": "支架不能在拆装中断开或消失；同一安装接口。",
    "group": "original",
    "status": "原有设定"
  },
  {
    "id": "E",
    "name": "织梦蛾",
    "en": "SOMNUS LOOM",
    "image": "collection_20260909/E_织梦蛾_专属面板.png",
    "hook": "收起是瓷质披风，展开用光丝织网。",
    "motion": "肩锁释放 → 上翼先张 → 下翼错层 → 线轴张丝",
    "controls": "翼形拨片、张力旋钮、梭形滑片",
    "fit": "四翼展开目标 ≤1.8D；不能缩小底座来突出翼展。",
    "group": "new",
    "status": "新增设定"
  },
  {
    "id": "F",
    "name": "拉格朗日天平",
    "en": "LAGRANGE BALANCE",
    "image": "collection_20260909/F_拉格朗日天平_专属面板.png",
    "hook": "两个配重越过平衡点，停在反常姿态。",
    "motion": "解除制动 → 连杆展开 → 越过平衡点 → 表针回稳",
    "controls": "制动拨杆、配平轮、方形脉冲键与指针表",
    "fit": "需验证闭环连杆；悬臂展开目标 ≤1.6D。",
    "group": "new",
    "status": "首批在制",
    "actual": "runtime_preview/F.png"
  },
  {
    "id": "G",
    "name": "折维书匣",
    "en": "PALIMPSEST ENGINE",
    "image": "collection_20260909/G_折维书匣_专属面板.png",
    "hook": "一本机械书，翻成层层错位的空间建筑。",
    "motion": "封扣退开 → 封盖打开 → 六页错峰 → 索引巡检",
    "controls": "页形拨片、棘齿索引轮、带护罩封存锁",
    "fit": "控制书脊高度和页片跨度；不得增加底盘层数。",
    "group": "new",
    "status": "首批在制",
    "actual": "runtime_preview/G.png"
  },
  {
    "id": "H",
    "name": "雷暴管风琴",
    "en": "TEMPEST ORGAN",
    "image": "collection_20260909/H_雷暴管风琴.png",
    "hook": "五根谐振管，将雷暴编成声光节拍。",
    "motion": "风门释放 → 背罩展开 → 五管点亮 → 电弧接力",
    "controls": "五枚短触键、风门旋钮、泄压拨杆",
    "fit": "五管应沿浅弧前后错位，不扩大底座。当前 ACTIVE 小图少一管，尚未通过状态一致性检查，选中后优先复核。",
    "group": "new",
    "status": "新增设定"
  },
  {
    "id": "I",
    "name": "回声海螺",
    "en": "HELIX AUDITOR",
    "image": "collection_20260909/I_回声海螺.png",
    "hook": "沿螺旋剥开的瓷壳，露出共振膜与音叉。",
    "motion": "喉闸打开 → 壳片顺次剥开 → 膜片共振 → 余音退去",
    "controls": "大调谐轮、喉闸拨杆、双脉冲触片",
    "fit": "螺壳沿深度布置；逐片验证铰链与回卷路径。",
    "group": "extra",
    "status": "首批在制",
    "actual": "runtime_preview/I.png"
  },
  {
    "id": "J",
    "name": "汞芽温室",
    "en": "MERCURY HERBARIUM",
    "image": "collection_20260909/J_汞芽温室.png",
    "hook": "三枝机械花，通过红色毛细管接力苏醒。",
    "motion": "主干伸长 → 枝条抬起 → 三芽错峰开 → 光脉冲回流",
    "controls": "三枚芽形键、泵送拨杆、脉冲旋钮",
    "fit": "同一中央安装座；生长通过伸缩关节完成。",
    "group": "extra",
    "status": "首批在制",
    "actual": "runtime_preview/J.png"
  },
  {
    "id": "K",
    "name": "星图刻写机",
    "en": "ASTROGRAPH SCRIBE",
    "image": "collection_20260909/K_星图刻写机.png",
    "hook": "卷轴与三支刻针，在金属带上刻出星图。",
    "motion": "双盖滑开 → 刻针落位 → 三臂接力刻写 → 卷轴回卷",
    "controls": "三枚短键、回车拨杆、送带滚轮",
    "fit": "双卷轴必须错层布置，不为横排卷轴扩大底座。",
    "group": "extra",
    "status": "首批在制",
    "actual": "runtime_preview/K.png"
  },
  {
    "id": "L",
    "name": "三相窥镜",
    "en": "TRIPHASE OBSERVATORY",
    "image": "collection_20260909/L_三相窥镜.png",
    "hook": "三支有不同脾气的潜镜，时而互看，时而对焦。",
    "motion": "镜颈伸出 → 三头搜寻 → 虹膜收紧 → 三束光汇合",
    "controls": "三枚镜头选择拨键、调焦滚轮、虹膜拨杆",
    "fit": "镜颈采用三角排布；交叉观察时保留净空。",
    "group": "extra",
    "status": "首批在制",
    "actual": "runtime_preview/L.png"
  },
  {
    "id": "M",
    "name": "星噬仪",
    "en": "ORRERY OF COLLAPSE",
    "image": "cosmic_devices/M_星噬仪_v3.png",
    "exploded": "cosmic_devices/M_开放收束_拆解.png",
    "design": "cosmic_devices/动作与特效设计_v3.md",
    "hook": "平时行星公转，启动后轨道收紧，三颗星依次被吞入。",
    "motion": "公转 → 螺旋内落 → 潮汐拉伸与吞噬 → 三星重构",
    "controls": "拟用轨道轮、星噬锁杆、重构键和拆装拨杆；图中按钮还未全部统一。",
    "fit": "沿用开放式三磁极硬件与相应拆解图，底座不扩大；控制器映射和行程仍需校正。",
    "group": "cosmic",
    "status": "首批在制",
    "control_plan": "cosmic_devices/控制器映射草案.md",
    "actual": "runtime_preview/M.png"
  },
  {
    "id": "N",
    "name": "裂隙回廊",
    "en": "SCHISM CORRIDOR",
    "image": "cosmic_devices/N_裂隙回廊_v3.png",
    "exploded": "cosmic_devices/N_裂隙回廊_拆解_v3.png",
    "design": "cosmic_devices/动作与特效设计_v3.md",
    "hook": "错位瓷骨扭开空间裂口，让同一件探针在另一端接续出现。",
    "motion": "闭缝 → 骨片扭开 → 喉道联通与对穿 → 黑膜回卷",
    "controls": "拟用联动开裂拨件、相位轮、探针键与拆装拨杆；旧按钮图标待改。",
    "fit": "两端不规则裂口前后错位，拆解以新版骨架为准；普通圆门版本已归档。",
    "group": "cosmic",
    "status": "首批在制",
    "control_plan": "cosmic_devices/控制器映射草案.md",
    "actual": "runtime_preview/N.png"
  }
];
