"""Build a portable review page from saved concepts and real EXE captures."""
import hashlib,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
out=ROOT/'production/interaction_refinement'
registry=json.loads((ROOT/'app/assets/collection/registry.json').read_text(encoding='utf-8'))
profiles=json.loads((ROOT/'app/assets/collection/control_profiles.json').read_text(encoding='utf-8'))['models']
items=[]
for m in registry['models']:
    ident=m['id']
    if ident=='B':continue
    path=out/'images'/f'{ident}_structure_controls.png'
    items.append(dict(id=ident,title=m['title'],concept=f'images/{path.name}',prompt=f'prompts/{ident}.txt',sha256=hashlib.sha256(path.read_bytes()).hexdigest(),runtime=f'../../review/interaction_native/release/{ident}_operating.png',controls=profiles[ident],status='第一轮机构精修；待继续校准' if ident=='F' else '控制已接入；上部模型待逐款精修'))
manifest=dict(date='2026-09-09',channel='subscription built-in image_gen',underlying_model='not exposed by tool; unverified',generated_images_are_runtime=False,models=items,corrections={'G':'prompts/G_panel_correction.txt','K':'Stylus is now a latching detent for one-pointer use; concept-panel correction pending.'})
(out/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
payload=json.dumps(items,ensure_ascii=False).replace('</','<\/')
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MagicDesk · 结构与控制复审</title>
<style>*{box-sizing:border-box}body{margin:0;background:#141311;color:#e7e1d6;font:15px/1.65 system-ui,"Microsoft YaHei",sans-serif}header,main{max-width:1600px;margin:auto;padding:26px 32px}header{border-bottom:1px solid #34312b}small,.muted{color:#a9a092}h1{font-size:29px;font-weight:500;letter-spacing:.04em;margin:6px 0}nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:22px}button{background:#22201c;color:#c9c0b1;border:1px solid #494239;padding:9px 16px;border-radius:5px;cursor:pointer}button[aria-selected=true]{background:#d7c6a8;color:#1b1813}h2{font-size:23px;margin:4px 0}.bar{display:flex;align-items:center;gap:16px;flex-wrap:wrap}label{color:#c2a87f}section{display:grid;grid-template-columns:1.55fr 1fr;gap:20px;margin-top:24px}.frame{background:#1a1917;border:1px solid #36322d;border-radius:8px;overflow:hidden}.frame strong{display:block;padding:12px 18px;font-weight:400;color:#d0b98f}.frame img{display:block;width:100%;height:590px;object-fit:contain;background:radial-gradient(ellipse at center,#35322c,#111110);cursor:zoom-in}.frame p{padding:0 18px;color:#9d9383;font-size:13px}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:20px}.control{border-top:1px solid #514335;padding:15px 5px}.control b{color:#e0c5a1}.control p{margin-top:5px;color:#b3aa9b}a{color:#dbc6a6}dialog{width:95vw;max-width:1800px;background:#161512;border:1px solid #71604a;color:white}dialog::backdrop{background:#000d}dialog img{max-height:87vh;width:100%;object-fit:contain}video{width:100%;max-height:650px;background:#111}footer{padding:32px;color:#8f877b;text-align:center}@media(max-width:850px){section{grid-template-columns:1fr}.frame img{height:auto}.controls{grid-template-columns:1fr}header,main{padding:20px}}</style>
<header><small>MAGICDESK / INTERACTION REVIEW / 2026.09.09</small><h1>让手上的动作，在机构里看得见。</h1><div class="muted">复古未来机械 · 同一底座 · 八款独立控制玩法</div><nav id="nav"></nav></header>
<main><div class="bar"><h2 id="title"></h2><label id="status"></label></div><section><div class="frame"><strong>01 / 设计目标 · 订阅内置生图</strong><img id="concept" alt="结构与控制设计图"><p>设计图用于规定方向。底层生图型号不可核验，未标为 Sunburst。</p></div><div class="frame"><strong>02 / Windows EXE 实际合成帧</strong><img id="runtime" alt="实际运行画面"><p>当前是交互评估版。实机与图稿的差距保留可见，未作为最终美术验收。</p></div></section><div id="controls" class="controls"></div>
<p class="muted">共用：右侧拆装拨杆左推拆解、右推组装，释放回中；最右 X 收拢并关闭。底座左前白色舱罩打开铭牌档案，滚轮翻阅。</p><details><summary>连续实机回放</summary><p class="muted">应用自身输入通道驱动并录制的实时合成画面，原速。不是概念动画，也不是人工鼠标录像。</p><video controls preload="metadata" src="../../review/interaction_native/release/review_walkthrough.mp4"></video></details><p><a href="README.md">制作状态</a> · <a id="prompt">原始提示词</a> · <a href="manifest.json">素材来源与校验</a></p></main><footer>共享底座：直径 2.740000 / 高度 0.670608。B 原模型保留。</footer><dialog id="zoom"><button onclick="document.getElementById('zoom').close()">关闭预览</button><img id="large"></dialog>
<script>const models=PAYLOAD;const $=id=>document.getElementById(id);function show(id){const m=models.find(x=>x.id===id);$('title').textContent=m.id+' / '+m.title;$('status').textContent=m.status;$('concept').src=m.concept;$('runtime').src=m.runtime;$('prompt').href=m.prompt;$('controls').replaceChildren(...m.controls.map(c=>{const d=document.createElement('div');d.className='control';const b=document.createElement('b');b.textContent=c.label;const p=document.createElement('p');p.textContent=c.hint;d.append(b,p);return d}));document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-selected',b.dataset.id===id));}for(const m of models){const b=document.createElement('button');b.textContent=m.id+' · '+m.title;b.dataset.id=m.id;b.onclick=()=>show(m.id);$('nav').append(b)}for(const id of ['concept','runtime'])$(id).onclick=()=>{$('large').src=$(id).src;$('zoom').showModal()};show('F');</script></html>'''.replace('PAYLOAD',payload)
(out/'index.html').write_text(page,encoding='utf-8')
print(out/'index.html')
